# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wolfare-event.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Thread
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(454, 394)
        self.newsRadButton = QtWidgets.QRadioButton(Form)
        self.newsRadButton.setGeometry(QtCore.QRect(20, 20, 70, 20))
        self.newsRadButton.setObjectName("newsRadButton")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 411, 281))
        self.scrollArea.setMaximumSize(QtCore.QSize(411, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.dataTextbox = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.dataTextbox.setGeometry(QtCore.QRect(0, 0, 411, 551))
        self.dataTextbox.setReadOnly(False)
        self.dataTextbox.setPlaceholderText("")
        self.dataTextbox.setObjectName("dataTextbox")
        self.newsTextbox = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.newsTextbox.setGeometry(QtCore.QRect(0, 0, 411, 551))
        self.newsTextbox.setReadOnly(True)
        self.newsTextbox.setPlaceholderText("")
        self.newsTextbox.setObjectName("newsTextbox")
        self.chatbotTextbox = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.chatbotTextbox.setGeometry(QtCore.QRect(0, 0, 411, 551))
        self.chatbotTextbox.setReadOnly(True)
        self.chatbotTextbox.setPlaceholderText("")
        self.chatbotTextbox.setObjectName("chatbotTextbox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.chatsRadButton = QtWidgets.QRadioButton(Form)
        self.chatsRadButton.setGeometry(QtCore.QRect(90, 20, 81, 20))
        self.chatsRadButton.setObjectName("chatsRadButton")
        self.dataRadButton = QtWidgets.QRadioButton(Form)
        self.dataRadButton.setGeometry(QtCore.QRect(180, 20, 101, 20))
        self.dataRadButton.setObjectName("dataRadButton")
        self.chatsHistory = QtWidgets.QComboBox(Form)
        self.chatsHistory.setGeometry(QtCore.QRect(330, 20, 104, 26))
        self.chatsHistory.setObjectName("chatsHistory")
        self.chatsHistory.addItem("")
        self.chatsHistory.addItem("")
        self.chatsHistory.addItem("")
        self.chatFrame = QtWidgets.QFrame(Form)
        self.chatFrame.setGeometry(QtCore.QRect(20, 340, 411, 31))
        self.chatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatFrame.setObjectName("chatFrame")
        self.askChatbot = QtWidgets.QTextEdit(self.chatFrame)
        self.askChatbot.setEnabled(True)
        self.askChatbot.setGeometry(QtCore.QRect(0, 0, 351, 31))
        self.askChatbot.setObjectName("askChatbot")
        self.sendButton = QtWidgets.QPushButton(self.chatFrame)
        self.sendButton.setGeometry(QtCore.QRect(350, 0, 61, 32))
        self.sendButton.setObjectName("sendButton")
        self.dataFrame = QtWidgets.QFrame(Form)
        self.dataFrame.setEnabled(True)
        self.dataFrame.setGeometry(QtCore.QRect(20, 340, 411, 31))
        self.dataFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataFrame.setObjectName("dataFrame")
        self.uploadButton = QtWidgets.QPushButton(self.dataFrame)
        self.uploadButton.setGeometry(QtCore.QRect(100, 0, 110, 32))
        self.uploadButton.setObjectName("uploadButton")
        self.finetuneButton = QtWidgets.QPushButton(self.dataFrame)
        self.finetuneButton.setGeometry(QtCore.QRect(200, 0, 110, 32))
        self.finetuneButton.setObjectName("finetuneButton")
        self.pushButton = QtWidgets.QPushButton(self.dataFrame)
        self.pushButton.setGeometry(QtCore.QRect(300, 0, 110, 32))
        self.pushButton.setObjectName("pushButton")
        self.clearButton = QtWidgets.QPushButton(self.dataFrame)
        self.clearButton.setGeometry(QtCore.QRect(0, 0, 110, 32))
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Wolfare Prime Service"))
        self.newsRadButton.setText(_translate("Form", "News"))
        self.chatsRadButton.setText(_translate("Form", "Chatbot"))
        self.dataRadButton.setText(_translate("Form", "Adding data"))
        self.chatsHistory.setItemText(0, _translate("Form", "History 1"))
        self.chatsHistory.setItemText(1, _translate("Form", "History 2"))
        self.chatsHistory.setItemText(2, _translate("Form", "History 3"))
        self.askChatbot.setPlaceholderText(_translate("Form", "Text to the chatbot"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.uploadButton.setText(_translate("Form", "Upload (.json)"))
        self.finetuneButton.setText(_translate("Form", "Fine-tune"))
        self.pushButton.setText(_translate("Form", "Push"))
        self.clearButton.setText(_translate("Form", "Clear"))
        # Event listeners
        self.newsRadButton.clicked.connect(lambda :self.openPanal(0))
        self.chatsRadButton.clicked.connect(lambda :self.openPanal(1))
        self.dataRadButton.clicked.connect(lambda :self.openPanal(2))
        # Fix the ui size
        Form.setFixedSize(454, 406)
        # News section init
        self.newsRadButton.setChecked(True)
        self.clearAllPanal()
        self.openPanal(0)
    
    def clearAllPanal(self):
        # Hide all text box
        self.newsTextbox.hide()
        self.chatbotTextbox.hide()
        self.dataTextbox.hide()
        # Hide frame
        self.chatFrame.hide()
        self.dataFrame.hide()
        # Hide misc.
        self.chatsHistory.hide()

    def openPanal(self, op):
        self.clearAllPanal()
        if op == 0: # News button was selected
            self.newsTextbox.show()
        if op == 1: # Chatbot button was selected
            self.chatbotTextbox.show()
            self.chatsHistory.show()
            self.chatFrame.show()
        if op == 2: # Adding Data button was selected
            self.dataTextbox.show()
            self.dataFrame.show()

if __name__ == "__main__":
    # Create the QApplication and Form
    global Form
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())